name: Check mergability

on:
  issue_comment:
    types: [created, edited]
  
jobs:
  check-mergability:
    permissions:
      contents: write
    uses: SFC-GH-TestOrg/CLAbot/.github/workflows/check-mergability.yml@main
    secrets: inherit
