name: Create comment workflow

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main
  
jobs:
  create-comment:
    permissions:
      statuses: write
      pull-requests: write
    uses: SFC-GH-TestOrg/CLAbot/.github/workflows/clabot-workflow.yml@main
