name: Create comment workflow

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main
  
jobs:
  create-comment:
    uses: SFC-GH-TestOrg/CLAbot/.github/workflows/clabot-workflow.yml@main
